# Generated by Django 5.0.2 on 2024-04-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='key',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
